apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
  # * Create namespace before use Deployment 
  namespace: ns-gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        # Image name:tag pulled from hub.docker.com/r/gitea/gitea
        - image: gitea/gitea:latest
          imagePullPolicy: IfNotPresent
          name: gitea
          ports:
            # SSH
            - containerPort: 22
              protocol: TCP
            # WEB
            - containerPort: 3000
              protocol: TCP
          # Local resources used for gitea-pod
          resources:
            requests:
              cpu: 1
              memory: 1000Mi
          volumeMounts:
          - mountPath: /var/tmp/gitea
            name: db-volume
      volumes:
      - name: db-volume
        hostPath:
          # directory location on host ( Linux )
          path: /var/tmp/gitea