pipeline {
    agent any
    stages {
        stage('Setup') {
            steps {
              script {
                    echo "This is Setup." 
                }  
            }
        }
    }
}