pipeline {
    agent any
    stages {
        stage('Bulid EC2') {
            steps {
              script {
                    echo "Setup EC2." 
                }  
            }
        }











    }
}